version: '3.7'

volumes:
  browser:


services:

  browser:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: 19.04
    image: zierf/firefox
    #ports:
    #  - "6000-6063:6000-6063"
    environment:
      DISPLAY: host.docker.internal:0.0
    volumes:
      - ./:/mnt
